[package]
name = "husky-crates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"]}
axum = "0.5.16"
anyhow = "1"
log = "0.4"
pretty_env_logger = { version = "0.4" }
sea-orm = "0.9.3"