[package]
name = "husky-packages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"]}
axum = "0.5.16"
hyper = "0.14.20"
thiserror = "1.0.37"
log = "0.4.17"
pretty_env_logger = { version = "0.4.0" }
sea-orm = "0.9.3"
git2 = "0.15.0"
url = { version = "2.3.1", features = ["serde"]}
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
config = "0.13.2"
clap = { version = "4.0.9", features = ["derive"] }
crates-io = { path = "../../../crates/crates-io" }
tempdir = "0.3.7"
zip = "0.6.2"
toml = "0.5.9"
bytes = "1.2.1"

[dev-dependencies]
reqwest = { version = "0.11.12", features = ["json"] }